# See https://www.apollographql.com/docs/federation/quickstart/#configuration-file
# for more info
subgraphs:
  parser-graphql-wrapper: 
    routing_url: https://parser-graphql-wrapper.getpocket.dev/
    # schema defines the introspection endpoint - usually the same, but it could be different
    schema:
      subgraph_url: https://parser-graphql-wrapper.getpocket.dev/
  # TODO: set up prospect api for federation!
  #prospect-api: 
  #  routing_url: https://prospect-api.getpocket.dev/
    # schema defines the introspection endpoint - usually the same, but it could be different
  #  schema:
  #    subgraph_url: https://prospect-api.getpocket.dev/
  # Uncomment/Add your subgraphs here to run locally
  # parser:
  #   routing_url: http://localhost:4001
  #   schema:
  #     subgraph_url: http://localhost:4001
  # user-api:
  #   routing_url: http://localhost:4006
  #   schema:
  #     subgraph_url: http://localhost:4006
