# See https://www.apollographql.com/docs/federation/quickstart/#configuration-file
# for more info
subgraphs:
  # Uncomment/Add your subgraphs here to run locally
  # parser:
  #   routing_url: http://localhost:4001
  #   schema:
  #     subgraph_url: http://localhost:4001
  # user-api:
  #   routing_url: http://localhost:4006
  #   schema:
  #     subgraph_url: http://localhost:4006
